name: Build OnePlus 8T Kernel with KernelSU

on:
  push:
    branches:
      - derp16-kebab-ksu-n-susfs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules via SSH
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        persist-credentials: false

    - name: Set up environment variables
      run: |
        echo "PATH=$HOME/toolchains/clang/bin:$PATH" >> $GITHUB_ENV
        echo "KERNEL_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "ARCH=arm
        
